### ISSUE TITLE
dom4j 2.3.1 does not exist

### ISSUE THREAD

**Issue by maokejackson** [GluuFederation/gluu-core-bom#19]
The dom4j version specified in dependency management is 2.3.1. I am not sure if it is a typo, but I found that the latest version in official website is [2.1.3](https://dom4j.github.io/).

**Comment by yuriyz** [comment]
Yes, you are right. Fixed https://github.com/GluuFederation/gluu-core-bom/commit/a84ec28db5628a7170479e37930f56238cc06f45

Thanks for report.
